spring.application.name=server-sent-event

# 替換成你的 API Key，若是內網模型則填入對應的憑證或留空
llm.api.key=anything_due_github_copilot_api_extension
# API 端點，如果是內網部署 (如 Ollama)，可以改為 http://localhost:11434/v1/chat/completions
#llm.api.url=https://api.openai.com/v1/chat/completions
llm.api.url=http://127.0.0.1:3030
llm.api.model=gpt-4o-copilot
